sections := "pure stats fs1 misc"

build-all: (_do-all "build")
clean-all: (_do-all "clean")

build target:
	TEXINPUTS=:{{justfile_directory()}}/styles latexmk -lualatex -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -synctex=1 -cd sections/{{target}}/main.tex
	cp sections/{{target}}/main.pdf pdfs/{{target}}.pdf

clean target:
	fd -I -e log -e aux -e dvi -e lof -e lot -e bit -e idx -e glo -e bbl -e bcf -e ilg -e toc -e ind -e out -e blg -e fdb_latexmk -e fls -e run.xml -e synctex.gz . 'sections/{{target}}' | xargs rm -f
	rm -f pdfs/{{target}}.pdf

_do-all recipe:
	@for sec in {{sections}}; do just {{recipe}} $sec; done
